FROM eclipse-temurin:17-jdk-alpine
COPY build/libs/RecommendationService-0.0.1-SNAPSHOT.jar RecommendationService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/RecommendationService-0.0.1-SNAPSHOT.jar"]