FROM eclipse-temurin:17-jdk-alpine
COPY build/libs/ConfigurationService-0.0.1-SNAPSHOT.jar ConfigurationService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/ConfigurationService-0.0.1-SNAPSHOT.jar"]