ALTER TABLE tour_note
    MODIFY price_detail_of_children TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    MODIFY regulation TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    MODIFY notes TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
INSERT INTO `tour_note` (`note_id`, `tour_id`, `price_detail_of_children`, `regulation`, `notes`)
VALUES (1, 4, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. 1'),
       (2, 2, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (3, 3, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (4, 1, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (5, 5, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (6, 6, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (7, 7, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (8, 8, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (9, 9, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (10, 10, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (11, 11, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (12, 12, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (13, 13, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (14, 14, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (15, 15, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (16, 16, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (17, 17, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (18, 18, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (19, 19, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (20, 20, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (21, 21, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (22, 22, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (23, 23, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (24, 24, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (25, 25, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (26, 26, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (27, 27, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (28, 28, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (29, 29, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (30, 30, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (31, 31, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (32, 32, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (33, 33, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (34, 34, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (35, 35, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (36, 36, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (37, 37, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (38, 38, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (39, 39, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (40, 40, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn trưa và nước uống trong suốt chuyến đi. '),
       (41, 41, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước 30 phút so với giờ khởi hành.',
        'Chúng tôi cung cấp bữa ăn nhẹ và nước uống trong suốt chuyến đi.'),
       (42, 42, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Chúng tôi yêu cầu khách tham gia mang theo giấy tờ tuỳ thân.',
        'Các điểm tham quan sẽ được thăm quan trong suốt chuyến đi.'),
       (43, 43, 'Giá cho trẻ em dưới 12 tuổi là 60% giá người lớn.',
        'Vui lòng mang theo giày thể thao hoặc giày dép dễ di chuyển.',
        'Bữa ăn trưa sẽ được cung cấp trong tour và có sẵn nước uống.'),
       (44, 44, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Chuyến đi có thể thay đổi lịch trình tùy theo thời tiết.',
        'Hướng dẫn viên sẽ hỗ trợ khách hàng trong suốt chuyến đi.'),
       (45, 45, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.', 'Vui lòng đến đúng giờ để không bỏ lỡ lịch trình.',
        'Chúng tôi sẽ cung cấp tài liệu hướng dẫn cho khách tham quan các điểm nổi bật.'),
       (46, 46, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng thông báo trước nếu có yêu cầu đặc biệt về ăn uống.',
        'Có thể có sự thay đổi về thời gian tham quan tùy thuộc vào điều kiện thực tế.'),
       (47, 47, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng mặc trang phục thoải mái và chuẩn bị đồ dùng cá nhân.',
        'Tour bao gồm các hoạt động ngoài trời, vì vậy vui lòng chuẩn bị sẵn các vật dụng cần thiết.'),
       (48, 48, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Chúng tôi sẽ không chịu trách nhiệm nếu khách hàng quên mang giấy tờ tùy thân.',
        'Các hoạt động trong chuyến đi sẽ được tổ chức theo nhóm.'),
       (49, 49, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần phải tuân thủ đầy đủ các quy định của các điểm tham quan.',
        'Chúng tôi có thể thay đổi thời gian tham quan trong trường hợp khẩn cấp.'),
       (50, 50, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần tự túc về phương tiện di chuyển đến điểm xuất phát.',
        'Tour sẽ bao gồm các bữa ăn nhẹ và các dịch vụ cần thiết.'),
       (51, 51, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng không mang theo đồ vật có giá trị hoặc quá cồng kềnh.',
        'Lịch trình có thể thay đổi do điều kiện thời tiết bất lợi.'),
       (52, 52, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng không hút thuốc trong khu vực tham quan và trên phương tiện di chuyển.',
        'Chúng tôi sẽ cung cấp các phương tiện vận chuyển tiện nghi trong suốt chuyến đi.'),
       (53, 53, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Chúng tôi không chịu trách nhiệm về bất kỳ sự mất mát nào trong chuyến đi.',
        'Chuyến đi sẽ diễn ra theo lịch trình đã được xác nhận trước.'),
       (54, 54, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng xác nhận lại thông tin chuyến đi 24 giờ trước khi khởi hành.',
        'Chúng tôi cung cấp dịch vụ hỗ trợ cho khách có yêu cầu đặc biệt.'),
       (55, 55, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Lịch trình có thể thay đổi tùy thuộc vào các yếu tố khách quan như thời tiết hoặc tình hình giao thông.',
        'Các chuyến tham quan được tổ chức vào các thời điểm đã xác định từ trước.'),
       (56, 56, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Các điểm tham quan có thể thay đổi tùy vào mùa và điều kiện thời tiết.',
        'Đảm bảo khách tham gia đi đúng giờ để chuyến đi diễn ra thuận lợi.'),
       (57, 57, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng mang theo thuốc men cá nhân nếu cần thiết trong suốt chuyến đi.',
        'Chúng tôi cung cấp bữa ăn nhẹ trên suốt hành trình và nước uống đầy đủ.'),
       (58, 58, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng thông báo về bất kỳ yêu cầu đặc biệt nào trước khi tham gia tour.',
        'Chuyến đi sẽ được điều chỉnh linh hoạt dựa trên tình hình thực tế của chuyến tham quan.'),
       (59, 59, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Lịch trình sẽ được xác nhận lại với khách hàng trước khi khởi hành.',
        'Chúng tôi cung cấp các thiết bị cần thiết cho chuyến đi và dịch vụ hỗ trợ khi có yêu cầu.'),
       (60, 60, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng không mang theo hành lý quá nặng và cồng kềnh.',
        'Chuyến đi sẽ bao gồm các điểm tham quan đẹp và dịch vụ đẳng cấp.'),
       (61, 61, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần phải tuân thủ các quy định của điểm tham quan.',
        'Chúng tôi sẽ cung cấp một số hướng dẫn và tài liệu cho khách tham quan trong suốt chuyến đi.'),
       (62, 62, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Chuyến đi có thể bị hoãn hoặc thay đổi nếu có điều kiện thời tiết không thuận lợi.',
        'Các bữa ăn sẽ được chuẩn bị theo yêu cầu và tùy vào loại tour.'),
       (63, 63, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần mang theo chứng minh nhân dân hoặc thẻ căn cước.',
        'Chúng tôi cung cấp các bữa ăn nhẹ và dịch vụ hỗ trợ khách hàng suốt chuyến đi.'),
       (64, 64, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.', 'Vui lòng mang theo bảo hiểm du lịch cá nhân.',
        'Chúng tôi sẽ hỗ trợ các khách hàng có yêu cầu đặc biệt về chế độ ăn uống.'),
       (65, 65, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần tuân thủ lịch trình của tour để tránh bị trễ chuyến.',
        'Bữa trưa sẽ được cung cấp trong suốt chuyến đi và có sẵn nước uống.'),
       (66, 66, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng mang theo thuốc men cá nhân nếu có yêu cầu đặc biệt.',
        'Các hoạt động trong tour sẽ diễn ra theo nhóm và có sự hướng dẫn từ các chuyên gia.'),
       (67, 67, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần phải có mặt tại điểm khởi hành trước 30 phút.',
        'Tour bao gồm các hoạt động thể thao ngoài trời, khách nên chuẩn bị trang phục phù hợp.'),
       (68, 68, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng mang theo áo mưa hoặc ô để chuẩn bị cho điều kiện thời tiết không thuận lợi.',
        'Hướng dẫn viên sẽ giải thích chi tiết về các điểm tham quan trong suốt chuyến đi.'),
       (69, 69, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần chuẩn bị sức khỏe tốt vì một số chuyến đi sẽ yêu cầu đi bộ dài.',
        'Chúng tôi sẽ cung cấp dịch vụ vận chuyển giữa các điểm tham quan trong suốt chuyến đi.'),
       (70, 70, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Chuyến đi có thể bị hủy hoặc thay đổi trong trường hợp thời tiết xấu.',
        'Chúng tôi cung cấp các thiết bị cần thiết cho chuyến tham quan và sẽ luôn hỗ trợ khách hàng khi cần thiết.'),
       (71, 71, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng không mang theo vật phẩm có giá trị để tránh mất mát.',
        'Chúng tôi sẽ cung cấp tài liệu hướng dẫn chi tiết về chuyến đi và các hoạt động.'),
       (72, 72, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách hàng cần phải có mặt đúng giờ để tránh lỡ chuyến đi.',
        'Bữa trưa sẽ được cung cấp tại các điểm dừng chân trong suốt hành trình tham quan.'),
       (73, 73, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Chuyến đi có thể thay đổi thời gian tùy thuộc vào điều kiện giao thông.',
        'Hướng dẫn viên sẽ chia sẻ thông tin về các địa điểm tham quan và văn hóa địa phương.'),
       (74, 74, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần phải mang theo chứng từ xác nhận đặt tour.',
        'Chúng tôi sẽ cung cấp một số món ăn đặc sản tại các địa phương trong suốt chuyến đi.'),
       (75, 75, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần chuẩn bị tiền mặt hoặc thẻ thanh toán cho các chi phí ngoài tour.',
        'Chuyến đi sẽ bao gồm các hoạt động tham quan và khám phá di sản văn hóa.'),
       (76, 76, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần phải xác nhận lại lịch trình 24 giờ trước khi khởi hành.',
        'Các điểm tham quan sẽ được thăm vào những thời gian đã được xác định từ trước.'),
       (77, 77, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng chuẩn bị sẵn các vật dụng cần thiết trong suốt chuyến đi.',
        'Chúng tôi sẽ cung cấp bữa ăn nhẹ và nước uống trong suốt hành trình tham quan.'),
       (78, 78, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần phải đi đúng giờ để tránh làm gián đoạn hành trình.',
        'Tour bao gồm các chuyến tham quan ở ngoài trời, khách nên chuẩn bị giày dép phù hợp.'),
       (79, 79, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng kiểm tra các quy định về giấy tờ trước khi tham gia tour.',
        'Bữa ăn trưa và các dịch vụ khác sẽ được cung cấp tùy theo yêu cầu của khách hàng.'),
       (80, 80, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần tham gia đầy đủ tất cả các hoạt động trong suốt chuyến đi.',
        'Chúng tôi có thể thay đổi lịch trình nếu có yêu cầu từ phía khách hàng hoặc điều kiện thời tiết không thuận lợi.'),
       (81, 81, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng mang theo thẻ bảo hiểm y tế trong trường hợp cần cấp cứu.',
        'Chuyến đi bao gồm các hoạt động dã ngoại và tham quan ngoài trời.'),
       (82, 82, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần tuân thủ nghiêm ngặt các quy định an toàn trong suốt chuyến đi.',
        'Chúng tôi cung cấp các dịch vụ hỗ trợ đặc biệt cho những khách hàng cần chăm sóc sức khỏe.'),
       (83, 83, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng mang theo thuốc men cá nhân và báo cho hướng dẫn viên nếu có yêu cầu đặc biệt.',
        'Hướng dẫn viên sẽ giải thích chi tiết về các điểm đến trong suốt chuyến đi.'),
       (84, 84, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần phải có mặt tại điểm khởi hành ít nhất 30 phút trước giờ xuất phát.',
        'Chúng tôi cung cấp các bữa ăn nhẹ và nước uống trong suốt chuyến tham quan.'),
       (85, 85, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Tour có thể bị thay đổi tùy thuộc vào điều kiện thời tiết hoặc tình hình giao thông.',
        'Chuyến đi sẽ bao gồm các hoạt động văn hóa và khám phá thiên nhiên.'),
       (86, 86, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần chuẩn bị trang phục thoải mái và giày dép phù hợp.',
        'Chúng tôi sẽ cung cấp các dịch vụ vận chuyển giữa các điểm tham quan trong suốt hành trình.'),
       (87, 87, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng mang theo tiền mặt cho các chi phí phát sinh trong suốt chuyến đi.',
        'Tour sẽ bao gồm các điểm tham quan nổi tiếng và các địa phương đặc trưng.'),
       (88, 88, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần tuân thủ lịch trình đã được xác định từ trước.',
        'Chúng tôi cung cấp các tài liệu hướng dẫn chi tiết về chuyến đi và các điểm đến tham quan.'),
       (89, 89, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Chuyến đi có thể thay đổi giờ khởi hành tùy thuộc vào tình hình giao thông và thời tiết.',
        'Chúng tôi hỗ trợ khách hàng với các yêu cầu đặc biệt về chế độ ăn uống.'),
       (90, 90, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần chuẩn bị một số vật dụng cá nhân như kem chống nắng, kính mát, và nón.',
        'Hướng dẫn viên sẽ chia sẻ thông tin về các điểm tham quan trong suốt chuyến đi.'),
       (91, 91, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng tuân thủ các chỉ dẫn an toàn trong suốt chuyến đi để đảm bảo sức khỏe và sự an toàn của tất cả mọi người.',
        'Chúng tôi cung cấp các dịch vụ hỗ trợ đặc biệt cho khách hàng có nhu cầu riêng.'),
       (92, 92, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách hàng cần có mặt đúng giờ để không bị lỡ chuyến đi.',
        'Bữa trưa sẽ được cung cấp tại các điểm dừng chân trong suốt hành trình tham quan.'),
       (93, 93, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng kiểm tra thông tin chi tiết về các điểm tham quan trước khi lên đường.',
        'Các hoạt động trong chuyến đi sẽ được tổ chức theo lịch trình có sẵn và hướng dẫn viên sẽ hỗ trợ khách hàng trong suốt hành trình.'),
       (94, 94, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần chuẩn bị sức khỏe tốt vì có thể phải đi bộ nhiều.',
        'Chúng tôi sẽ hỗ trợ khách hàng trong việc di chuyển và tham quan các điểm đến trong suốt chuyến đi.'),
       (95, 95, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần kiểm tra lại các giấy tờ và vé tour trước khi tham gia chuyến đi.',
        'Chuyến đi sẽ bao gồm các hoạt động văn hóa và tham quan thiên nhiên đặc sắc của địa phương.'),
       (96, 96, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Chuyến đi sẽ được tổ chức đúng giờ và khách cần có mặt tại điểm khởi hành ít nhất 30 phút trước giờ xuất phát.',
        'Chúng tôi cung cấp các dịch vụ ăn uống và giải khát trong suốt chuyến đi để đảm bảo sự thoải mái cho khách hàng.'),
       (97, 97, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần chuẩn bị các vật dụng cá nhân cần thiết như thuốc men, trang phục thoải mái, và đồ dùng cá nhân.',
        'Chúng tôi cung cấp dịch vụ hỗ trợ khách hàng với yêu cầu đặc biệt về chế độ ăn uống hoặc sức khỏe.'),
       (98, 98, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng đảm bảo tuân thủ các quy định về thời gian và điểm xuất phát để chuyến đi diễn ra suôn sẻ.',
        'Bữa ăn sẽ được cung cấp tại các điểm nghỉ dừng chân trong suốt hành trình tham quan.'),
       (99, 99, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần tuân thủ các chỉ dẫn an toàn để đảm bảo chuyến đi diễn ra an toàn và vui vẻ.',
        'Hướng dẫn viên sẽ giải thích các thông tin chi tiết về các điểm tham quan trong suốt chuyến đi.'),
       (100, 100, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần kiểm tra lại vé và giấy tờ trước khi tham gia chuyến đi.',
        'Tour sẽ bao gồm các hoạt động tham quan và khám phá các địa điểm du lịch nổi tiếng trong khu vực.'),
       (101, 101, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần có mặt trước giờ khởi hành ít nhất 30 phút.',
        'Chuyến đi sẽ bao gồm các hoạt động ngoài trời, vui lòng chuẩn bị trang phục thoải mái.'),
       (102, 102, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng chuẩn bị sẵn sàng và tuân thủ đúng thời gian xuất phát để chuyến đi không bị gián đoạn.',
        'Chúng tôi cung cấp các bữa ăn nhẹ và nước uống suốt chuyến đi.'),
       (103, 103, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần mang theo thẻ bảo hiểm y tế trong trường hợp cần cấp cứu.',
        'Chuyến đi bao gồm các hoạt động thể thao và tham quan di tích lịch sử.'),
       (104, 104, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng mang theo tiền mặt cho các chi phí cá nhân phát sinh.',
        'Tour sẽ khám phá các điểm du lịch nổi tiếng với những hoạt động giải trí thú vị.'),
       (105, 105, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần kiểm tra các giấy tờ tùy thân và vé tour trước khi khởi hành.',
        'Các bữa ăn được cung cấp theo yêu cầu của khách hàng, với các lựa chọn đa dạng.'),
       (106, 106, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Chuyến đi có thể bị thay đổi tùy thuộc vào điều kiện thời tiết và các yếu tố bất khả kháng khác.',
        'Chúng tôi cung cấp dịch vụ hỗ trợ đặc biệt cho khách hàng có nhu cầu về sức khỏe.'),
       (107, 107, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng tuân thủ nghiêm ngặt các quy định về an toàn trong suốt chuyến đi.',
        'Hướng dẫn viên sẽ chia sẻ thông tin thú vị về các địa điểm tham quan trong suốt hành trình.'),
       (108, 108, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Chúng tôi yêu cầu khách hàng có mặt tại điểm xuất phát đúng giờ để không làm gián đoạn lịch trình.',
        'Tour sẽ bao gồm các hoạt động tham quan nổi tiếng và các món ăn đặc sản của địa phương.'),
       (109, 109, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần chuẩn bị sức khỏe tốt vì một số hoạt động có thể yêu cầu đi bộ dài.',
        'Chúng tôi cung cấp dịch vụ vận chuyển giữa các điểm tham quan để đảm bảo sự tiện lợi cho khách.'),
       (110, 110, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần tuân thủ các chỉ dẫn an toàn để bảo vệ sức khỏe của mình và của mọi người.',
        'Tour sẽ bao gồm các hoạt động văn hóa, thể thao và giải trí đặc sắc trong suốt hành trình.'),
       (111, 111, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần chuẩn bị các vật dụng cá nhân như thuốc men, kính mát, và kem chống nắng.',
        'Chúng tôi cung cấp các dịch vụ hỗ trợ đối với những yêu cầu đặc biệt về chế độ ăn uống.'),
       (112, 112, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng đảm bảo rằng bạn tuân thủ đúng các quy định về thời gian và lịch trình của chuyến đi.',
        'Chuyến đi sẽ bao gồm các điểm tham quan ngoài trời và các hoạt động trải nghiệm đặc sắc.'),
       (113, 113, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần có mặt tại điểm xuất phát đúng giờ và chuẩn bị các vật dụng cá nhân cần thiết.',
        'Chúng tôi cung cấp các bữa ăn nhẹ và nước uống trong suốt chuyến đi để khách cảm thấy thoải mái.'),
       (114, 114, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần mang theo các giấy tờ tùy thân như chứng minh thư hoặc hộ chiếu.',
        'Hướng dẫn viên sẽ cung cấp thông tin chi tiết về các điểm tham quan trong suốt chuyến đi.'),
       (115, 115, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần tuân thủ các quy định an toàn trong suốt chuyến đi và đảm bảo sức khỏe tốt.',
        'Chúng tôi cung cấp dịch vụ vận chuyển giữa các điểm tham quan để đảm bảo chuyến đi diễn ra suôn sẻ.'),
       (116, 116, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng tuân thủ các chỉ dẫn và quy định trong suốt chuyến đi để đảm bảo an toàn cho bạn và người khác.',
        'Chuyến đi sẽ khám phá các địa điểm du lịch nổi tiếng, với các hoạt động giải trí đặc sắc.'),
       (117, 117, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng chuẩn bị trang phục thoải mái và giày dép phù hợp cho các hoạt động ngoài trời.',
        'Tour bao gồm các hoạt động dã ngoại, tham quan các điểm du lịch nổi tiếng và thưởng thức các món ăn địa phương.'),
       (118, 118, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần chuẩn bị sẵn sàng và tuân thủ đúng thời gian và lịch trình.',
        'Chúng tôi cung cấp các dịch vụ hỗ trợ khách hàng với yêu cầu đặc biệt về chế độ ăn uống hoặc di chuyển.'),
       (119, 119, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần chuẩn bị các vật dụng cá nhân cần thiết cho chuyến đi và tuân thủ quy định an toàn.',
        'Tour sẽ bao gồm các hoạt động khám phá thiên nhiên và tham quan các địa điểm văn hóa đặc sắc.'),
       (120, 120, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần có mặt tại điểm xuất phát đúng giờ và chuẩn bị các vật dụng cá nhân như thuốc men, kem chống nắng, và kính mát.',
        'Chúng tôi cung cấp các dịch vụ ăn uống và hỗ trợ khách hàng trong suốt chuyến đi để đảm bảo sự thoải mái tối đa.'),
       (121, 121, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần có mặt trước giờ khởi hành ít nhất 15 phút để làm thủ tục đăng ký.',
        'Chuyến đi bao gồm các hoạt động tham quan di tích lịch sử, vui lòng mang giày thể thao thoải mái.'),
       (122, 122, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng tuân thủ đúng giờ xuất phát để đảm bảo không bỏ lỡ các hoạt động đã lên lịch.',
        'Tour sẽ bao gồm các chuyến tham quan cảnh quan thiên nhiên và thưởng thức đặc sản địa phương.'),
       (123, 123, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần mang theo các giấy tờ tùy thân cần thiết và thẻ bảo hiểm nếu có.',
        'Chúng tôi cung cấp dịch vụ chăm sóc sức khỏe nếu khách hàng có nhu cầu.'),
       (124, 124, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng giữ vệ sinh chung và không làm phiền các hành khách khác trong suốt chuyến đi.',
        'Tour bao gồm các hoạt động tham quan các địa điểm du lịch nổi tiếng và các trò chơi giải trí thú vị.'),
       (125, 125, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần chuẩn bị sức khỏe tốt, đặc biệt là cho các hoạt động đi bộ dài.',
        'Chuyến đi sẽ bao gồm các chuyến thăm di tích văn hóa và thưởng thức ẩm thực đặc sắc.'),
       (126, 126, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần phải đến sớm để kiểm tra vé và chỗ ngồi.',
        'Chúng tôi cung cấp bữa ăn trong suốt chuyến đi và hỗ trợ khách với yêu cầu đặc biệt.'),
       (127, 127, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng tuân thủ các quy định về bảo vệ môi trường và giữ gìn vệ sinh chung.',
        'Tour sẽ đưa khách tham quan các điểm du lịch hấp dẫn, có hướng dẫn viên giải thích chi tiết về lịch sử địa phương.'),
       (128, 128, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần mang theo giấy tờ tùy thân và các vật dụng cá nhân cần thiết.',
        'Chúng tôi cung cấp các bữa ăn nhẹ và nước uống suốt chuyến đi để khách cảm thấy thoải mái.'),
       (129, 129, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần lưu ý các hoạt động có thể thay đổi tùy theo thời tiết.',
        'Chuyến đi sẽ bao gồm các hoạt động tham quan, chụp ảnh và tham gia các trò chơi thú vị.'),
       (130, 130, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng tuân thủ đúng lịch trình để tránh bị lỡ các điểm tham quan quan trọng.',
        'Tour sẽ gồm các chuyến thăm các địa điểm nổi bật và các bữa ăn đặc sản địa phương.'),
       (131, 131, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần có mặt đúng giờ và chuẩn bị các vật dụng cá nhân như thuốc men và kem chống nắng.',
        'Tour bao gồm các hoạt động thăm quan ngoài trời và thưởng thức các món ăn đặc sản của vùng miền.'),
       (132, 132, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng chuẩn bị đầy đủ các giấy tờ cần thiết và kiểm tra lại vé trước chuyến đi.',
        'Chuyến đi sẽ bao gồm các hoạt động tham quan thiên nhiên và các địa điểm lịch sử nổi tiếng.'),
       (133, 133, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần chuẩn bị sức khỏe tốt và mang theo các vật dụng cá nhân cần thiết.',
        'Chúng tôi cung cấp các dịch vụ hỗ trợ khách hàng đặc biệt trong suốt chuyến đi.'),
       (134, 134, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng đảm bảo bạn tuân thủ các quy định an toàn và tránh những hành động gây nguy hiểm cho chính mình và người khác.',
        'Chúng tôi cung cấp các bữa ăn miễn phí và nước uống trong suốt chuyến đi để đảm bảo sự thoải mái cho khách hàng.'),
       (135, 135, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần chuẩn bị trang phục thoải mái và giày thể thao cho các hoạt động ngoài trời.',
        'Tour sẽ khám phá các địa điểm du lịch nổi tiếng và có các hoạt động giải trí hấp dẫn.'),
       (136, 136, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng tuân thủ các quy định về vệ sinh và bảo vệ môi trường trong suốt chuyến đi.',
        'Chúng tôi cung cấp các dịch vụ hỗ trợ đặc biệt cho những khách có yêu cầu về chế độ ăn uống hoặc di chuyển.'),
       (137, 137, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần tuân thủ lịch trình và các quy định an toàn trong suốt chuyến đi.',
        'Chuyến đi sẽ đưa khách tham quan các địa điểm di tích văn hóa và thưởng thức ẩm thực đặc sản.'),
       (138, 138, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần mang theo các giấy tờ tùy thân như chứng minh nhân dân hoặc hộ chiếu.',
        'Chúng tôi cung cấp dịch vụ vận chuyển giữa các điểm tham quan để đảm bảo chuyến đi diễn ra thuận lợi.'),
       (139, 139, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng tuân thủ các quy định về an toàn và bảo vệ sức khỏe trong suốt chuyến đi.',
        'Tour bao gồm các hoạt động thể thao và tham quan các di tích nổi tiếng trong khu vực.'),
       (140, 140, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần chuẩn bị các vật dụng cá nhân như kem chống nắng, mũ, và kính mát.',
        'Chúng tôi cung cấp các bữa ăn nhẹ và các dịch vụ hỗ trợ khách hàng trong suốt chuyến đi.'),
       (141, 141, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần có mặt trước giờ khởi hành ít nhất 15 phút để làm thủ tục đăng ký.',
        'Chuyến đi bao gồm các hoạt động thăm quan di tích lịch sử và các trò chơi giải trí thú vị.'),
       (142, 142, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần mang theo giấy tờ tùy thân và các vật dụng cá nhân cần thiết.',
        'Chuyến đi sẽ bao gồm các chuyến tham quan các điểm du lịch nổi tiếng và thưởng thức các món ăn đặc sản.'),
       (143, 143, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng tuân thủ đúng giờ và chuẩn bị các vật dụng cá nhân như thuốc men và kem chống nắng.',
        'Chúng tôi cung cấp các dịch vụ đặc biệt cho khách có nhu cầu về chế độ ăn uống hoặc hỗ trợ khác.'),
       (144, 144, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần chuẩn bị sức khỏe tốt và tham gia các hoạt động theo nhóm.',
        'Chuyến đi sẽ bao gồm các hoạt động ngoài trời và tham quan các địa điểm di tích văn hóa.'),
       (145, 145, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần lưu ý về các quy định về bảo vệ môi trường và giữ gìn vệ sinh chung.',
        'Tour sẽ khám phá các cảnh đẹp tự nhiên và thưởng thức ẩm thực đặc sản của địa phương.'),
       (146, 146, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng tuân thủ các quy định về an toàn và bảo vệ sức khỏe trong suốt chuyến đi.',
        'Chuyến đi sẽ đưa khách tham quan các địa điểm di tích nổi tiếng và các khu vực bảo tồn thiên nhiên.'),
       (147, 147, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần chuẩn bị trang phục thoải mái và giày thể thao cho các hoạt động ngoài trời.',
        'Chúng tôi cung cấp các dịch vụ hỗ trợ đặc biệt cho khách hàng có yêu cầu riêng.'),
       (148, 148, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần mang theo các giấy tờ tùy thân và các vật dụng cá nhân cần thiết cho chuyến đi.',
        'Tour bao gồm các chuyến tham quan các điểm di tích lịch sử và thưởng thức ẩm thực địa phương.'),
       (149, 149, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần chuẩn bị sức khỏe tốt, đặc biệt cho các hoạt động đi bộ dài.',
        'Tour sẽ đưa khách tham quan các địa điểm nổi bật và có các hoạt động giải trí hấp dẫn.'),
       (150, 150, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng chuẩn bị các giấy tờ tùy thân cần thiết và kiểm tra lại vé trước chuyến đi.',
        'Chuyến đi sẽ bao gồm các hoạt động tham quan, chụp ảnh và tham gia các trò chơi thú vị.'),
       (151, 151, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần chuẩn bị các vật dụng cá nhân như thuốc men, kem chống nắng và kính mát.',
        'Chúng tôi cung cấp các bữa ăn nhẹ và nước uống suốt chuyến đi.'),
       (152, 152, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần tuân thủ các quy định về an toàn trong suốt chuyến đi.',
        'Tour sẽ gồm các chuyến thăm các địa điểm du lịch nổi tiếng và các hoạt động vui chơi giải trí.'),
       (153, 153, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt trước giờ khởi hành để đảm bảo lịch trình không bị thay đổi.',
        'Chúng tôi cung cấp các dịch vụ hỗ trợ đặc biệt cho khách có nhu cầu di chuyển hoặc chế độ ăn uống riêng.'),
       (154, 154, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần tuân thủ các quy định bảo vệ môi trường và giữ gìn vệ sinh chung trong suốt chuyến đi.',
        'Chuyến đi sẽ bao gồm các hoạt động tham quan di tích văn hóa, ẩm thực và trải nghiệm các trò chơi thú vị.'),
       (155, 155, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần mang theo các giấy tờ tùy thân như chứng minh nhân dân hoặc hộ chiếu.',
        'Chúng tôi cung cấp các dịch vụ vận chuyển giữa các điểm tham quan và cung cấp các bữa ăn nhẹ.'),
       (156, 156, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần có mặt đúng giờ để làm thủ tục và nhận hướng dẫn về chuyến đi.',
        'Tour sẽ bao gồm các hoạt động ngoài trời, thăm các di tích lịch sử và tham gia các trò chơi thú vị.'),
       (157, 157, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần chuẩn bị trang phục thoải mái và giày thể thao cho các chuyến tham quan dài.',
        'Chúng tôi cung cấp các bữa ăn và dịch vụ hỗ trợ khách hàng suốt chuyến đi.'),
       (158, 158, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần mang theo các vật dụng cá nhân cần thiết như thuốc men và kính mát.',
        'Chuyến đi sẽ bao gồm các chuyến tham quan các điểm du lịch nổi bật và thưởng thức ẩm thực đặc sắc.'),
       (159, 159, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần lưu ý về các quy định an toàn và bảo vệ sức khỏe trong suốt chuyến đi.',
        'Chúng tôi cung cấp các bữa ăn nhẹ và dịch vụ hỗ trợ cho khách có yêu cầu đặc biệt.'),
       (160, 160, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng tuân thủ lịch trình và các quy định an toàn trong suốt chuyến đi.',
        'Tour sẽ đưa khách tham quan các địa điểm văn hóa nổi tiếng và các khu vực thiên nhiên tuyệt đẹp.'),
       (161, 161, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần chuẩn bị đầy đủ các vật dụng cá nhân và kiểm tra lại các giấy tờ cần thiết trước chuyến đi.',
        'Chúng tôi cung cấp các dịch vụ vận chuyển và bữa ăn miễn phí trong suốt chuyến đi.'),
       (162, 162, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng có mặt sớm để làm thủ tục và nhận các thông tin liên quan đến chuyến đi.',
        'Chuyến đi sẽ bao gồm các hoạt động khám phá các địa điểm du lịch nổi tiếng và thưởng thức các món ăn đặc sản.'),
       (163, 163, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần chuẩn bị sức khỏe tốt và tham gia các hoạt động ngoài trời.',
        'Chúng tôi cung cấp các dịch vụ đặc biệt cho khách hàng có yêu cầu riêng về chế độ ăn uống hoặc di chuyển.'),
       (164, 164, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần tuân thủ các quy định về bảo vệ môi trường và an toàn trong suốt chuyến đi.',
        'Chuyến đi sẽ bao gồm các chuyến tham quan các di tích lịch sử và các khu vực thiên nhiên tuyệt đẹp.'),
       (165, 165, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần mang theo các giấy tờ tùy thân và các vật dụng cá nhân cần thiết cho chuyến đi.',
        'Chúng tôi cung cấp các dịch vụ hỗ trợ khách hàng đặc biệt trong suốt chuyến đi.'),
       (166, 166, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng chuẩn bị sức khỏe tốt và các vật dụng cá nhân như thuốc men và kem chống nắng.',
        'Tour bao gồm các chuyến thăm các địa điểm du lịch và thưởng thức các món ăn đặc sản của vùng.'),
       (167, 167, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần tuân thủ lịch trình và các quy định an toàn trong suốt chuyến đi.',
        'Chuyến đi sẽ đưa khách tham quan các địa điểm du lịch nổi tiếng và các khu vực bảo tồn thiên nhiên.'),
       (168, 168, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia tour cần chuẩn bị các vật dụng cá nhân và kiểm tra lại vé trước chuyến đi.',
        'Chuyến đi bao gồm các hoạt động tham quan, chụp ảnh và các trò chơi vui nhộn.'),
       (169, 169, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách cần mang theo các giấy tờ tùy thân và các vật dụng cá nhân cần thiết cho chuyến đi.',
        'Tour sẽ bao gồm các hoạt động tham quan và thưởng thức các món ăn đặc sắc của vùng.'),
       (170, 170, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần chuẩn bị sức khỏe tốt và các vật dụng cá nhân như thuốc men và kem chống nắng.',
        'Chuyến đi sẽ đưa khách tham quan các di tích văn hóa và thưởng thức các món ăn đặc sản.'),
       (171, 171, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần tuân thủ các quy định về an toàn và bảo vệ sức khỏe trong suốt chuyến đi.',
        'Chúng tôi cung cấp các dịch vụ vận chuyển và hỗ trợ khách hàng trong suốt chuyến đi.'),
       (172, 172, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần chuẩn bị các vật dụng cá nhân và các giấy tờ cần thiết cho chuyến đi.',
        'Chuyến đi bao gồm các hoạt động thăm quan và thưởng thức các món ăn đặc sản.'),
       (173, 173, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Vui lòng chuẩn bị sức khỏe tốt và các vật dụng cá nhân như thuốc men, kem chống nắng.',
        'Chuyến đi bao gồm các chuyến tham quan di tích lịch sử và các hoạt động giải trí thú vị.'),
       (174, 174, 'Giá cho trẻ em dưới 12 tuổi là 50% giá người lớn.',
        'Khách tham gia cần tuân thủ các quy định về an toàn và bảo vệ môi trường.',
        'Tour sẽ khám phá các địa điểm du lịch nổi bật và thưởng thức các món ăn đặc sản tại các vùng miền.');
