name: Deploy to EC2

on:
  push:
    branches:
      - main  # Chạy khi có push lên nhánh main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Bước 1: Clone mã nguồn từ repository
      - name: Checkout source code
        uses: actions/checkout@v4

        # Bước 2: Dừng tất cả container đang chạy
      - name: Stop all running containers
        run: |
          docker ps -q | xargs -r docker stop

      # Bước 3: Sửa quyền thư mục redis-data
      - name: Fix permissions for redis-data
        run: |
          sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/Project_Booking_Tour_BE/Project_Booking_Tour_BE/redis-data
          sudo chmod -R 755 /home/ubuntu/actions-runner/_work/Project_Booking_Tour_BE/Project_Booking_Tour_BE/redis-data

      # Bước 4: Dọn dẹp thư mục redis-data
      - name: Clean redis-data directory
        run: |
          sudo rm -rf /home/ubuntu/actions-runner/_work/Project_Booking_Tour_BE/Project_Booking_Tour_BE/redis-data

      # Bước 5: Dọn dẹp Docker volumes không sử dụng
      - name: Clean up Docker volumes
        run: |
          docker volume prune -f
      
      # Bước 7: Build mới và chạy lại Docker Compose
      - name: Run docker-compose
        run: |
          cd /home/ubuntu/actions-runner/_work/Project_Booking_Tour_BE/Project_Booking_Tour_BE
          # Build lại các container với image mới
          docker-compose build
          
          # Dừng và xóa các container cũ
          docker-compose down
          
          # Khởi động lại container với image mới
          docker-compose up -d
          

