name: Deploy to EC2

on:
  push:
    branches:
      - main  # Chạy khi có push lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Clone mã nguồn từ repository
      - name: Checkout source code
        uses: actions/checkout@v4

       # Bước 2: Kiểm tra đường dẫn thư mục hiện tại
      - name: Print current directory
        run: |
          echo "Current directory:"
          pwd

      - name: Copy code to EC2
        run: |
          scp -r /home/runner/work/Project_Booking_Tour_BE/Project_Booking_Tour_BE ubuntu@47.128.230.99:/home/ubuntu/Travel_Project 

      # Bước 3: Kiểm tra cấu trúc thư mục
      - name: List files to check where the source code is located
        run: |
          echo "Listing files in the current directory:"
          ls -la

      # Bước 5: SSH vào EC2 và chạy Docker Compose
      # - name: Deploy services
      #   run: |
      #     # cd /home/ubuntu/
      #     docker-compose down
      #     docker-compose up -d
      #     EOF
